apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    io.kompose.service: consumer
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: consumer