apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 29092
      name: internal
      targetPort: 29092
    - port: 9092
      name: external
      targetPort: 9092
  selector:
    io.kompose.service: kafka
